groups:
- name: build
  jobs:
  - testflight
  - rc
  - shipit
- name: version
  jobs:
  - patch
  - minor
  - major

jobs:
- name: testflight
  public: true
  serial: true
  plan:
  - do:
    - aggregate:
      - get: lockpick
        resource: git-lockpick
      - get: git-lockpick-release-changes
        trigger: true
    - task: run_tests
      config:
        platform: linux
        image: {{docker-hub-task-image}}
        inputs:
        - name: lockpick
          path: .
        run:
          path: ./ci/scripts/run_tests.sh
          args: []

- name: rc
  public: true
  plan:
  - aggregate:
    - get: lockpick
      resource: git-lockpick
      passed: [testflight]
      trigger: true
    - get: version
      trigger: false
      params: {bump: minor, pre: rc}
  - put: version
    params: {file: version/number}

- name: patch
  public: true
  plan:
  - aggregate:
    - get: version
      trigger: false
      params: {bump: patch}
  - put: version
    params: {file: version/number}

- name: minor
  public: true
  plan:
  - aggregate:
    - get: version
      trigger: false
      params: {bump: minor}
  - put: version
    params: {file: version/number}

- name: major
  public: true
  plan:
  - aggregate:
    - get: version
      trigger: false
      params: {bump: major}
  - put: version
    params: {file: version/number}

- name: shipit
  public: true
  serial: true
  plan:
  - aggregate:
    - get: version
      passed: [rc]
      params: {bump: final}
    - get: lockpick
      resource: git-lockpick
      passed: [rc]
  - task: create-final-release
    config:
      platform: linux
      image: {{docker-hub-task-image}}
      inputs:
      - name: lockpick
      - name: version
      run:
        path: ./lockpick-boshrelease/ci/scripts/shipit.sh
        args: []
      params:
        release_name: "Lockpick Release"
        promotion_branch: master
  - put: git-lockpick
    params:
      repository: create-final-release/lockpick-release
      rebase: true
  - aggregate:
    - put: version
      params: {file: version/number}
    - put: github-final-release
      params:
        name: create-final-release/lockpick-boshrelease/releases/name
        tag: create-final-release/lockpick-boshrelease/releases/tag
        body: create-final-release/lockpick-boshrelease/releases/notes.md
        globs:
        - create-final-release/lockpick-boshrelease/releases/*/lockpick-*.tar.gz
        - create-final-release/lockpick-boshrelease/releases/*/lockpick.zip
        - create-final-release/lockpick-boshrelease/releases/*/LICENSE
        - create-final-release/lockpick-boshrelease/releases/*/README.md


resources:
- name: version
  type: semver
  source:
    key: current-version
    bucket: {{pipeline-aws-bucket}}
    access_key_id: {{pipeline-aws-access-key-id}}
    secret_access_key: {{pipeline-aws-secret-access-key}}
    initial_version: 0.1.0

- name: git-lockpick
  type: git
  source:
    uri: git@github.com:longnguyen11288/lockpick.git
    branch: master
    private_key: {{github-private-key}}

- name: git-lockpick-release-changes
  type: git
  source:
    uri: https://github.com/longnguyen11288/lockpick.git
    branch: master
    paths: ["*.go"]

- name: github-final-release
  type: github-release
  source:
    user: longnguyen11288
    repository: lockpick
    access_token: {{github-access-token}}
